In [16]:
import numpy as np
import cv2


def cva_usingDistance(img1,img2):
    (row1,col1,dim1)=img1.shape
    (row2,col2,dim2)=img2.shape
    print(row1,col1)
    if dim1!=dim2:
        print("维度不同，无法比较")
    temp_img1=img1
    temp_img2=img2
    #创建两个二维矩阵来存放数据
    matrix_CVA= np.array([[0.0]*col1 for i in range(row1)])
    matrix_SCM = np.array([[0.0]*col1 for i in range(row1)])
    print(matrix_CVA.shape)    
    SCM=0.0  # SCM 存放光谱角
    tagSum=0.0
    tagEum=0.0
    s1=0.0
    s2=0.0
    Ax = 0.0
    Ay1 = 0.0
    Ay2 = 0.0
    Ay3 =0.0
    A=0.0 #A存放余弦值
    mean_t1=0.0 #计算平均值
    mean_t2=0.0
    for i in range(row1):
        for j in range(col1):
            tagSum=0.0
            Ax=0.0
            Ay1=0.0
            Ay2=0.0
            Ay3=0.0
            A =0.0
            SAD = 0.0
            mean_t1=(img1[i,j,0]+img1[i,j,1]+img1[i,j,2])/3.0
            mean_t2=(img2[i,j,0]+img2[i,j,1]+img2[i,j,2])/3.0            
            for k in range(dim1):
                Ax+=int(img1[i,j,k]-mean_t1)*int(img2[i,j,k]-mean_t2)
                Ay1+=int(img1[i,j,k]-mean_t1)*int(img1[i,j,k]-mean_t1)
                Ay2+=int(img2[i,j,k]-mean_t2)*int(img2[i,j,k]-mean_t2)
                s1=int(img1[i,j,k])
                s2=int(img2[i,j,k]) 
                tagEum=abs(s1-s2)
                agSum+=tagEum*tagEum
            Ay1=math.sqrt(Ay1)
            Ay2=math.sqrt(Ay2)
            Ay3=Ay1*Ay2
            
            
            if Ay1==0 or Ay2==0:
                SCM=0
            elif Ax==0: # 内积为0
                SCM=90
            else:
                A=Ax/Ay3
                #print(A)
                AA=abs(A-1)
                if AA<1e-7:
                    SCM=0
                else:
                    SCM=math.acos(A)*180.0/3.1415926
            
            tagSum=math.sqrt(tagSum)
            
                
    

[[3 5 2 8]
 [4 6 2 4]]
1.243163121016122
1.2431631210161223
2.1320071635561044
2.4494897427831783
2.2763607319179844
2.2763607319179844


In [10]:
x = np.array([[3,4],[5,6],[2,2],[8,4]])

In [11]:
x

array([[3, 4],
       [5, 6],
       [2, 2],
       [8, 4]])

In [12]:
xT=x.T

In [13]:
xT

array([[3, 5, 2, 8],
       [4, 6, 2, 4]])

In [14]:
D=np.cov(xT)# 求协方差矩阵

In [15]:
D

array([[7.        , 2.        ],
       [2.        , 2.66666667]])

In [23]:
import numpy as np


def mashi_distance(x,y):
    print (x)
    print (y)
    #马氏距离要求样本数要大于维数，否则无法求协方差矩阵
    #此处进行转置，表示10个样本，每个样本2维
    X=np.vstack([x,y])

    print(X)
    XT=X.T

    print (XT)

    #方法一：根据公式求解
    S=np.cov(X)   #两个维度之间协方差矩阵
    SI = np.linalg.inv(S) #协方差矩阵的逆矩阵
    #马氏距离计算两个样本之间的距离，此处共有4个样本，两两组合，共有6个距离。
    n=XT.shape[0]
    d1=[]
    for i in range(0,n):
        for j in range(i+1,n):
            delta=XT[i]-XT[j]
            d=np.sqrt(np.dot(np.dot(delta,SI),delta.T))
            print(d)
            d1.append(d)


if __name__ == '__main__':
    # 第一列
    x = [255,45,66]

    # 第二列
    y = [255,45,65]

    mashi_distance(x,y)



[255, 45, 66]
[255, 45, 65]
[[255  45  66]
 [255  45  65]]
[[255 255]
 [ 45  45]
 [ 66  65]]
2.0000000000033538
2.0000000000004547
1.9999999999932179
